### ISSUE TITLE
Using MathJax and other libraries

### ISSUE THREAD

**Issue by jadarve** [zzossig/hugo-theme-zdoc#30]
Hi,

I really like this theme. I'm using it for documenting my project https://lluvia.io/

I need to include MathJax for rendering some equations. I see that in https://github.com/zzossig/hugo-theme-zdoc/blob/master/layouts/partials/script/single-script.html there is a reference to MathJax, but not sure how to enable it.

I tried including the code below in my `config/_default/params.toml` but still the formulas do not render.

```
Libraries = ["mathjax"]
```

What's the correct way to include those libraries defined in `single-script.html`?

**Comment by graille** [comment]
Hello,
Don't know if you found your answer, but this is the answer for other people:

Just add a "libraries" tag in your page header:

`---
title: Test page
date: 2019-05-16T19:04:43+02:00
libraries: ['katex']
---`

I recommend using Katex instead of Mathjax (faster and cleaner).
**Note: it seems this tag is not working in Hugo 0.69.0 (and earlier version), because "Libraries" seems to be a reserved param name. But it's working fine with Hugo 0.72.0**

**Comment by jadarve** [comment]
Hi @graille, thanks for the answer. I didn't know that was the way include libraries. I tried Katex and it works correctly.
