### ISSUE TITLE
Tags in Doc site [Feature Request]

### ISSUE THREAD

**Issue by edhilgendorf** [zzossig/hugo-theme-zdoc#35]
Is this planned for future releases? I've noticed if I add tags to the doc site they do show up in the blog site, but when you click they don't have the correct format (blog format)

It's possible I'm implementing it wrong as well. Thanks, I love this theme and your work.

**Comment by zzossig** [comment]
I thought that `tags` only need on the blog-type page. (blog type is a default type)
The URL starting with `/blog` is a `blog` type.
The URL starting with `/docs` is a `docs` type.

> I've noticed if I add tags to the doc site they do show up in the blog site, but when you click they don't have the correct format (blog format)

It's because the URL(the link) starts with `/docs` maybe. It means the MD file is in the `docs` folder in your project.

Since one page(one MD file) can't have two types(should choose blog or docs), make the same files to the `blog` folder. And if necessary, change the type to `blog`
```yaml
---
title: "my blog post from the docs folder"
...
type: blog
---
my contents
```

**Comment by edhilgendorf** [comment]
I see -- some doc sites DO support tags, here is a bad example from a static site generator I am moving away from to ZDoc:
https://ansible.hilgendorf.me/#orgd35209a

In this instance they are broken (can't be clicked to filter) but that is the expected functionality. Would it be possible to implement shared tags? Or separate tags for docs and blog? Thanks so much.

**Comment by zzossig** [comment]
> Would it be possible to implement shared tags?

Tags are already shared so that the docs tags appear on the blog page

> Or separate tags for docs and blog

I think it's possible.

At the very beginning that I designed this theme, I considered only blog-page tags.
And now I understand it could be good for the docs-page too.
But where to put the docs-page tags?

This?
![화면 캡처 2020-10-30 161312](https://user-images.githubusercontent.com/52706977/97671146-0afd7c80-1acb-11eb-823a-8dc065e94ff6.png)
Or this?
![화면 캡처 2020-10-30 161443](https://user-images.githubusercontent.com/52706977/97671148-0c2ea980-1acb-11eb-8a37-7d38f109d68e.png)

**Comment by edhilgendorf** [comment]
The second is what I see most common, as long as it does not replace "What's in this page" , because that is really nice for browsing/index!

**Comment by zzossig** [comment]
I'll consider more which place is the best and I'll do some work on it tomorrow.

**Comment by zzossig** [comment]
I'm sorry but I confront the same problem.
> One page(one MD file) can't have two types(should choose blog or docs)

It was possible to separate the tags from the blog and docs by making another taxonomy - Categories or Series
But If we want to serve the docs page in blog type, we should make the file in the blog folder.

**Comment by edhilgendorf** [comment]
Actually... As is works pretty well. I DO have tags in my Docs pages already, and they show up in the blog tags, and when I click one it takes me directly to the Docs page for it. Is there anyway to just add a tags index to the right side, or somewhere on the Docs site?Thanks!

**Comment by zzossig** [comment]
I have a question.
Why do you want to use `tags` on both the document page and the blog page?
Why not use another taxonomy one each other?
It's very difficult(it's Hugo design) to share the same taxonomy to different section pages (doc, blog).

As you can see, all tags share the URL(/tags). So it's very difficult to know where the tags are from(docs? or blog?)
![화면 캡처 2020-11-02 165115](https://user-images.githubusercontent.com/52706977/97842839-a856eb80-1d2b-11eb-84bd-659a801150c3.png)
We can discriminate it by adding a URL alias in the markdown file but I don't want to add that much complexity to this theme.

So I suggest that if you want to use taxonomy(like tags) just use another taxonomy(categories, series, etc)
If it is fine with you, I can develop it.

**Comment by edhilgendorf** [comment]
I'm new to Hugo, need to read up on Taxonomies. A different one, like "category", etc, would work. The reasoning to share the same would be you could want to see about a tag "programming" and could see docs in addition to any blog posts that are related, in one place. But I think categories, or something, would work great in docs site! Thanks so much, I look forward to your updates.

**Comment by BeenaCelin** [comment]
Hi Hugo team,
I have enabled categories to our site created on top of zdoc theme. Unfortunately, few of the category links are not listing out inner content list. can you share videos/tutorials which explains this.
